### ISSUE TITLE
Error with installation custom-react-scripts

### ISSUE THREAD

**Issue by badenkov** [kitze/create-react-app#20] opened 2016-10-05 11:22 UTC
Hello! I'm trying to use your fork. But everytime I've got an error when npm install dependencies:

```bash
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/user/.nvm/versions/node/v6.6.0/bin/node" "/Users/user/.nvm/versions/node/v6.6.0/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! Path must be a string. Received undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Projects/lim/front/npm-debug.log
```

I've tried two ways:
At first I've created app from scratch:

```bash
create-react-app my-app --scripts-version custom-react-scripts
```

At second times I've done

```bash
create-react-app my-app
```

and then change devDependencies

from 

```json
"react-scripts": "0.6.0"
```

to

```json
"custom-react-scripts": "0.0.14"
```

And everytime I've got same error.
I have
* node v6.6.6
* npm v3.10.8

Thanks and best wishes!

**Comment by PKief** [comment] 2016-10-05 14:05
Hi, I've got the same error on Windows 7
node v6.7.0
npm v3.10.3

**Comment by seanrasmussen** [comment] 2016-10-05 14:54
I also can't seem to get it working on Windows 7:

`Installing packages. This might take a couple minutes.
Installing react-scripts from npm...

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sea
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-
exact" "custom-react-scripts"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.8

npm ERR! Path must be a string. Received undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request
npm ERR!     C:\Users\Sean\Documents\Code\CustomReact\my-app\npm-de
`npm install --save-dev --save-exact custom-react-scripts` failed`

**Comment by jbach** [comment] 2016-10-05 15:11
This is a duplicate of https://github.com/kitze/create-react-app/issues/13.

**Comment by kitze** [comment] 2016-10-06 10:54
Closing this one because it's a duplicate. Let's continue the [discussion here](https://github.com/kitze/create-react-app/issues/13).

**Closed by kitze** 2016-10-06 10:54 UTC
